### PR TITLE
50 reduce binaries size

### PR DESCRIPTION
**Pull request by danielsiegl**
It works and reduces the file size to aroudn 50% or less - hard to explain why some thing like remove prerendred diagrams is 80MB at the moment ;) 

==> Downside in the current way of things jet doesn't seem to work anymore.

### CODE REVIEW

**Comment by danielsiegl** [comment]
Rebased with the new Build Scripts

**Comment by danielsiegl** [comment]
We need to enhance the build and run tests on the other DB releated tool aka Remove Prerendered Diagrams also with Jet and Sqlite

**Comment by danielsiegl** [comment]
@joHerbst72 I think we shall change the Windows builds to be none "Self Contained"

**Comment by joHerbst72** [comment]
> @joHerbst72 I think we shall change the Windows builds to be none "Self Contained"
> 
> This will ensure none trimmed .exe's for windows and Jet support - only question is do we get a proper message on things like build agents if the framework is not installed.

I will check tomorrow Friday.

do I need some new task?
or shall I continue "reduce binary-size" task/branch (as pushing brings anyway some errors)?

**Comment by joHerbst72** [comment]
updated build.yml to set publishing parameters for each target:
grafik

**Result:** 
`win-x86`: single-exe, not self-contained
`linux-x64`: single-exe, self-contained, trimmed

**Pull request merged**
